version: '3.1'

services:

  wordpress:
    build:
      context: ./.docker/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    env_file: .env
    ports:
      - 8000:80    
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wpdb
    volumes: 
      - ./wordpress:/var/www/html
      - ./.docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wp

  db:
    image: mysql:5.7
    restart: always
    env_file: .env

    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - wp
networks:
  wp:
  
volumes:
  wordpress:
  db:
   
    