name: Digital Ocean Deploy

on:
  push:
    branches: [ master]

jobs:
  Build:
    runs-on: self-hosted
  
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Create .env
      run:  echo 'PORT=${{ secrets.PORT }}' > .env

    - name: Run build
        un: docker-compose up -d
