name: Digital Ocean Deploy

on:
  push:
    branches: [ master]

jobs:
  Build:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run:  echo 'PORT=${{ secrets.PORT }}' > .env

      - name: Run build
        run: docker-compose up -d
